replicaCount: 1

image:
  repository: darren606/demo-app
  pullPolicy: IfNotPresent
  tag: "1.0.0"  # default; we will override this with VERSION later

service:
  type: ClusterIP
  port: 3000

resources: {}
